name: run-tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Update system packages
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
      - name: Install dependencies
        run: |
          sudo apt-get install -y python3 python3-venv btrfs-progs zfsutils-linux
      - name: Setup SSH
        env:
          SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >~/.ssh/known_hosts 2>/dev/null
          chmod 0600 ~/.ssh/known_hosts
      - name: Create virtual environment
        run: |
          python3 -m venv yaesm-venv
      - name: Activate and run pytest environment
        run: |
          source yaesm-venv/bin/activate
          pip3 install -e .[test]
          python3 -m pytest
